@startuml
!include <C4/C4_Component>

LAYOUT_WITH_LEGEND()

title TripTop - Frontend Component Diagram

Person(browser, "Browser", "User interacts via web UI")

    Component(loginComponent, "Login Component", "Handles user authentication")
    Component(reisplannerComponent, "Reisplanner Component", "Handles trip planning")
    Component(bouwstenenLijstComponent, "Bouwstenen Lijst Component", "Displays available building blocks")

    Rel(browser, reisplannerComponent, "Interacts with")
    Rel(browser, loginComponent, "Interacts with")


Container_Ext(api_gateway, "API Gateway", "Routes API calls")
Container_Ext(wiremock, "WireMock", "Mock server for login testing")

    Rel_L(loginComponent, wiremock, "Login request")
    Rel(reisplannerComponent, api_gateway, "Calls Reisplanner API")
    Rel_R(reisplannerComponent, bouwstenenLijstComponent, "Fetches building blocks list")
    Rel(bouwstenenLijstComponent, api_gateway, "Calls Reisplanner API")




@enduml
