@startuml
!include <C4/C4_Component>

!define DottedRel(from,to,label) from -[dashed]-> to : label
!define DottedRel_U(from,to,label) from -[dashed]up-> to : label
!define DottedRel_D(from,to,label) from -[dashed]down-> to : label
!define DottedRel_L(from,to,label) from -[dashed]left-> to : label
!define DottedRel_R(from,to,label) from -[dashed]right-> to : label

title TripTop -  Backend component Diagram
Boundary(system, "Triptop", "Backend Systeem"){
    Component(controller, "BouwsteenController","Spring boot Controller", "Handles API requests")
    Component(repo, "BouwsteenRepository", "Spring Boot Repository", "Verstuurt bouwsteenen naar de database")
    Component(service, "BouwsteenService", "Spring boot Service", "Bevat logica om acties uit te voeren bij een bepaalde staat van een bouwsteen")
}
Container(frontend, "Frontend", "React.JS", "Webapplicatie waar reiziger de reis kan plannen")
ContainerDb(db, "Database", "MongoDB" ,Slaat data op van de reis)
DottedRel(service, repo, "gebruikt")
Rel_R(repo, db, Slaat Bouwsteen op, MongoDB Wire Protocol)
Rel(frontend, controller, doet API-verzoek, HTTP/JSON)
Rel(controller, service, "gebruikt")
SHOW_LEGEND()
@enduml