@startuml
!include <C4/C4_Component>


$addRelTagToLegend(D_Rel, "black", "gray", $DASHED_LINE, Not always executed, dashed line)

!unquoted procedure D_Rel($from, $to, $label, $techn="", $descr="", $sprite="", $tags="D_Rel", $link="", $direction = "")
!if ($direction == right)
    $getRel(("-[dashed]right->>"), $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!elseif ($direction == left)
    $getRel(("-[dashed]left->>"), $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!elseif ($direction == up)
    $getRel(("-[dashed]up->>"), $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!elseif ($direction == down)
    $getRel(("-[dashed]down->>"), $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!else
    $getRel("-[dashed]->>", $from, $to, $label, $techn, $descr, $sprite, $tags, $link)
!endif
increment()
!endprocedure

!unquoted procedure D_Rel_R($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
D_Rel($from, $to, $label, $techn, $descr, $sprite, D_Rel, $link, right)
!endprocedure

!unquoted procedure D_Rel_L($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
D_Rel($from, $to, $label, $techn, $descr, $sprite, D_Rel, $link, left)
!endprocedure

!unquoted procedure D_Rel_U($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
D_Rel($from, $to, $label, $techn, $descr, $sprite, D_Rel, $link, up)
!endprocedure

!unquoted procedure D_Rel_D($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
D_Rel($from, $to, $label, $techn, $descr, $sprite, D_Rel, $link, down)
!endprocedure

title TripTop -  Backend component Diagram
Boundary(system, "Triptop", "Backend Systeem"){
    Component(controller, "BouwsteenController","Spring boot Controller", "Handles API requests")
    Component(repo, "BouwsteenRepository", "Spring Boot Repository", "Verstuurt bouwsteenen naar de database")
    Component(service, "BouwsteenService", "Spring boot Service", "Bevat logica om acties uit te voeren bij een bepaalde staat van een bouwsteen")
}
Container(frontend, "Frontend", "React.JS", "Webapplicatie waar reiziger de reis kan plannen")
ContainerDb(db, "Database", "MongoDB" ,Slaat data op van de reis)
D_Rel(service, repo, "gebruikt")
Rel_R(repo, db, Slaat Bouwsteen op, MongoDB Wire Protocol)
Rel(frontend, controller, doet API-verzoek, HTTP/JSON)
Rel(controller, service, "gebruikt")
SHOW_LEGEND()
@enduml