@startuml
title TripTop Restaurant API Sequence
actor Gebruiker
participant "BouwsteenController : bouwsteenController" as controller
participant "BouwsteenService : bouwsteenService" as service
participant "RestaurantService : restaurantService" as restaurantService
participant "RestaurantAPI : restaurantAPI" as restaurantAPI
Gebruiker -> controller : getAlleRestaurants("Amsterdam")
controller -> service : getAlleRestaurantsOpLocatie("Amsterdam")
    alt service instanceOf RestaurantService
                service -> restaurantService : getBouwstenen("Amsterdam")
        loop api in apis
             restaurantService -> restaurantAPI : List<Bouwsteen> bouwstenen = overAPICallUit("Amsterdam")
        end

restaurantService --> service: List<Bouwsteen> bouwstenen
service --> controller : List<Bouwsteen>  bouwstenen
controller --> Gebruiker : List<Bouwsteen> bouwstenen
            end

@enduml