@startuml
title Sequentiediagram: Wijzigen van BouwsteenStatus

actor Gebruiker
participant "BouwsteenService" as BsService
participant "Bouwsteen" as Bs
participant "Geregeld" as BSSgeregeld
database "BouwsteenRepository" as DB

Gebruiker -> BsService: updateBouwsteen(bouwsteenId, actie)
BsService -> DB: bouwsteen = findById(bouwsteenId)
BsService -> Bs: voerUit(actie, bouwsteen)
Bs -> BSSgeregeld: betaal(bouwsteen)
Bs <-- BSSgeregeld: setState(betaald)
Bs --> BsService: bouwsteen
BsService -> DB: updateBouwsteen(bouwsteen)
BsService --> Gebruiker: bouwsteen

@enduml
