@startuml
title Triptop Class Diagram

class BouwsteenService{
  +getAlleRestaurantsOpLocatie(location : String) : List<Bouwsteen>
  +getRouteNaarBouwsteen(bouwsteen : Bouwsteen)
}

class BouwsteenRepository {
}
abstract class Bouwsteen {
    - naam : String
    - type : String
    - link : String
    - info : String
    - locatie : Locatie
}

class Restaurant
note left: Per dienst een andere klasse en andere extra inhoud

interface ApiService{
    getBouwstenen(locatie : String) : List<Bouwsteen>
}

class KaartenService{
    +getNaam(location : Location) : String
    +getCoordinaten(location : String) : Locatie
}

abstract class API <T> {
    restTemplate : RestTemplate
    voerAPICallUit(<E>) : <T>
}

abstract class APIMetLocatie < T >

class BouwsteenController {
    +getAlleRestaurants(locatie : String)
    +getRouteBouwsteen(id: int)
}

class UberEats
class Thuisbezorgd
class GoogleMapsPlaces
class TrueWayDirection
class RestaurantService
note left: Per dienst een andere klasse en andere extra inhoud

BouwsteenService -->"- bouwstenen" Bouwsteen
Bouwsteen ^-- Restaurant
BouwsteenService -->" - services" ApiService
ApiService ^-- RestaurantService
API ^-- APIMetLocatie
APIMetLocatie ---> "- kaartenservice" KaartenService
APIMetLocatie ^-- UberEats
APIMetLocatie ^-- Thuisbezorgd
ApiService ^-- KaartenService
RestaurantService --> "-apis" APIMetLocatie
API ^-- TrueWayDirection
API ^-- GoogleMapsPlaces
KaartenService -->"- trueWayDirection" TrueWayDirection
KaartenService ->"- googleMapsPlaces" GoogleMapsPlaces
BouwsteenService --> "- bouwsteenRepository" BouwsteenRepository
@enduml