@startuml

hide circle
skinparam classAttributeIconSize 0

title TripTop ApiGateway RequestInterceptor class diagram

interface GlobalFilter <<interface>> {
    + filter(ServerWebExchange exchange, GatewayFilterChain chain)
}
note "Komt van Spring Cloud Gateway" as filterNote

filterNote .. GlobalFilter

interface PriorityOrdered <<interface>> {
    + getOrder()
}

filterNote .. PriorityOrdered

class InboundRequestFilter {
}

class RestTemplate{
}

note "Komt van Spring Boot" as restTemplateNote
restTemplateNote .. RestTemplate

class AuthStrategyFactory {
    + AuthStrategy getStrategy(String strategyType)
}

abstract class AuthStrategy <<abstract class>> {
    - boolean authenticate(Map<String, String>: headers)
}

class GoogleAuthStrategy {}
note "Een voorbeeld auth strategy die gemaakt kan worden" as googleAuthStrategyNote
googleAuthStrategyNote ..left GoogleAuthStrategy

InboundRequestFilter -up-^ GlobalFilter
InboundRequestFilter -up-^ PriorityOrdered
InboundRequestFilter --right> "- authStrategyFactory" AuthStrategyFactory

AuthStrategyFactory ..> AuthStrategy : <<creates>>
InboundRequestFilter ..> AuthStrategy : <<uses>>

AuthStrategy --up> "- restTempalte" RestTemplate

GoogleAuthStrategy -up-^ AuthStrategy


@enduml